# =============================================================
# Cloud Build CI pipeline
# Buduje obraz Dockera i aktualizuje manifest w env-repo (GitOps)
# =============================================================

steps:
# -------------------------------------------------------------
# 1️⃣ Build Docker image
# -------------------------------------------------------------
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
    [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/myapp:$SHORT_SHA',
      '.'
    ]

# -------------------------------------------------------------
# 2️⃣ Push image to Artifact Registry
# -------------------------------------------------------------
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
    [
      'push',
      '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/myapp:$SHORT_SHA'
    ]

# -------------------------------------------------------------
# 3️⃣ Clone env-repo from GitHub and update deployment manifest
# -------------------------------------------------------------
- name: 'gcr.io/cloud-builders/git'
  id: Clone and Update env-repo
  entrypoint: bash
  args:
    - '-ceu'
    - |
      set -x
      git config --global user.email "ci-bot@$PROJECT_ID.iam.gserviceaccount.com"
      git config --global user.name "Cloud Build Bot"

      # ✅ Clone env-repo securely using GitHub token (stored as secret)
      git clone https://${_GITHUB_TOKEN}@github.com/twixy1905-stack/env-repo.git
      cd env-repo
      git checkout ${_ENV_BRANCH}

      # ✅ Update Docker image reference in deployment manifest
      sed -i "s|image:.*|image: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/myapp:$SHORT_SHA|g" k8s/deployment.yaml

      # ✅ Commit and push the updated manifest
      git add k8s/deployment.yaml
      git commit -m "Update image to $SHORT_SHA via Cloud Build"
      git push https://${_GITHUB_TOKEN}@github.com/twixy1905-stack/env-repo.git ${_ENV_BRANCH}

# -------------------------------------------------------------
# Optional: declare built image for tracking in Cloud Build UI
# -------------------------------------------------------------
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/myapp:$SHORT_SHA'

# -------------------------------------------------------------
# Variables (substitutions)
# -------------------------------------------------------------
substitutions:
  _REGION: us-central1
  _AR_REPO: my-repo
  _ENV_REPO: env-repo
  _ENV_BRANCH: main
  _GITHUB_TOKEN: ""   # <- To będzie podstawiane automatycznie z sekretu w Cloud Build

# -------------------------------------------------------------
# Logging (recommended)
# -------------------------------------------------------------
options:
  logging: CLOUD_LOGGING_ONLY
